
name: Build and Release (Windows)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --noconsole --onefile --name goanduisp .\app\app.py

      - name: Archive artifacts
        run: |
          mkdir dist_out
          powershell Compress-Archive dist/goanduisp.exe dist_out/goanduisp-windows.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-windows
          path: dist_out/*

  release:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist_all

      - name: Extract version from app/app.py
        id: get_version
        run: |
          $content = Get-Content app/app.py
          $pattern = '__version__\s*=\s*["\'']([\d\.]+)["\'']'
          $match = $content | Select-String -Pattern $pattern
          if ($match) {
            $version = $match.Matches[0].Groups[1].Value
            echo "version=$version" >> $env:GITHUB_OUTPUT
          } else {
            Write-Error "Version not found"
            exit 1
          }

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: "Release ${{ steps.get_version.outputs.version }}"
          files: dist_all/**/*
          update_existing: true
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}